(function(){
const enToZv={
  hello:'Šævra',greetings:'Ðøren',goodbye:'Krävul',i:'Në',me:'Në',you:'Vü',he:'Ën',she:'Ën',they:'Ënra',we:'Nëm',us:'Nëm',friend:'Drøk',friends:'Drøken',home:'Käv',house:'Käv',city:'Şevar',water:'Ulv',fire:'Røk',earth:'Zæn',sky:'Aşra',night:'Nøkt',day:'Ræva',good:'Mëla',bad:'Durg',big:'Grön',small:'Neli',fast:'Sæva',slow:'Toma',strange:'Qæzar',strong:'Bruk',weak:'Løven',go:'Varn',went:'Varnø',going:'Varna',come:'Kelm',came:'Kelmø',coming:'Kelmæ',see:'Dævr',eat:'Xøra',drink:'Nuvş',build:'Sæk',have:'Dær',love:'Drøklæv',say:'Ƶær',be:'Bë',am:'Bë',are:'Bë',is:'Bë',was:'Bë',were:'Bë',no:'Næ',yes:'Ära',game:'VæƵ','let’s':'Vrëm',"let's":'Vrëm',play:'VæƵ',goes:'Varnor',will:'Varnul',mamad:'Møža'
};
const zvToEn={};Object.entries(enToZv).forEach(([en,zv])=>{if(!zvToEn[zv])zvToEn[zv]=en});
const faToEn={"سلام":"hello","درود":"greetings","خداحافظ":"goodbye","من":"I","تو":"you","او":"he/she","ما":"we","شما":"you","آنها":"they","دوست":"friend","دوستان":"friends","خانه":"home","شهر":"city","آب":"water","آتش":"fire","زمین":"earth","آسمان":"sky","شب":"night","روز":"day","خوب":"good","بد":"bad","بزرگ":"big","کوچک":"small","سریع":"fast","کند":"slow","عجیب":"strange","قوی":"strong","ضعیف":"weak","رفتن":"go","رفتم":"went","رفت":"went","می‌روم":"I am going","میروم":"I am going","می‌روی":"you are going","میروی":"you are going","می‌رود":"he/she is going","میرود":"he/she is going","خواهم رفت":"I will go","آمدن":"come","آمدم":"I came","آمد":"came","می‌آیم":"I am coming","میام":"I am coming","دیدن":"see","می‌بینم":"I see","میبینم":"I see","خوردن":"eat","می‌خورم":"I eat","میخورم":"I eat","نوشیدن":"drink","می‌نوشم":"I drink","مینوشم":"I drink","ساختن":"build","دارم":"I have","داشتن":"have","دوست داشتن":"love","دوستت دارم":"I love you","گفتن":"say","هستم":"I am","هستی":"you are","هست":"is","بودن":"be","هستیم":"we are","هستید":"you are","هستند":"they are","نه":"no","نمی":"not","آره":"yes","بله":"yes","بازی":"game","بریم":"let's go","ممد":"Mamad"};
const enToFa={};Object.entries(faToEn).forEach(([fa,en])=>{if(!enToFa[en])enToFa[en]=fa});
const norm=s=>s.normalize('NFC').replace(/[’‘]/g,"'").trim();
function wordTranslate(text,map){let out=norm(text);const keys=Object.keys(map).sort((a,b)=>b.length-a.length);for(const k of keys){const re=new RegExp('(?<![A-Za-z])'+k.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')+'(?![A-Za-z])','gi');out=out.replace(re,()=>map[k])}return out.replace(/\s+/g,' ').replace(/\s+([,!.?])/g,'$1').trim()}
function translateENtoZV(s){return wordTranslate(s,enToZv)}
function translateZVtoEN(s){return wordTranslate(s,zvToEn)}
function translateENtoFA(s){return wordTranslate(s,enToFa)}
function translateFAtoEN(s){return wordTranslate(s,faToEn)}
let languageFrom='fa',languageTo='zv';
function translateAny(s){if(languageFrom==='fa'&&languageTo==='zv')return translateFA(s);if(languageFrom==='zv'&&languageTo==='fa')return translateZV(s);if(languageFrom==='en'&&languageTo==='zv')return translateENtoZV(s);if(languageFrom==='zv'&&languageTo==='en')return translateZVtoEN(s);if(languageFrom==='en'&&languageTo==='fa')return translateENtoFA(s);if(languageFrom==='fa'&&languageTo==='en')return translateFAtoEN(s);return s}
function labels(){return {fa:'فارسی',en:'English',zv:'ژاڤرک'}}
function renderMode(){const a=labels();document.getElementById('fromLang').textContent=a[languageFrom];document.getElementById('toLang').textContent=a[languageTo];document.getElementById('inputTag').textContent='INPUT · '+languageFrom.toUpperCase();document.getElementById('outputTag').textContent='OUTPUT · '+languageTo.toUpperCase();const p={fa:'مثلاً: ممد بریم بازی؟',en:'e.g. I love you.',zv:'مثلاً: Në Vü Drøklæv'};document.getElementById('input').placeholder=p[languageFrom];document.getElementById('input').dir=languageFrom==='fa'?'rtl':'ltr';document.getElementById('output').dir=languageTo==='fa'?'rtl':'ltr';document.getElementById('output').style.textAlign=languageTo==='fa'?'right':'left'}
function update3(){const input=document.getElementById('input'),output=document.getElementById('output'),status=document.getElementById('status'),s=input.value;output.value=s?translateAny(s):'';document.getElementById('inputCount').textContent=`${s.length.toLocaleString('fa-IR')} نویسه`;document.getElementById('outputCount').textContent=`${output.value.length.toLocaleString('fa-IR')} نویسه`;status.textContent=s?`ترجمه آماده است؛ ${output.value.length.toLocaleString('fa-IR')} نویسه خروجی ساخته شد.`:'آماده‌ام؛ متن را بنویس.'}
function setLanguages(from,to){languageFrom=from;languageTo=to;renderMode();document.getElementById('output').value='';update3()}
const toolbar=document.querySelector('.mode');toolbar.innerHTML='<select class="mode-badge" id="fromSelect" aria-label="زبان مبدأ"><option value="fa">فارسی</option><option value="en">English</option><option value="zv">ژاڤرک</option></select><span>→</span><select class="mode-badge" id="toSelect" aria-label="زبان مقصد"><option value="zv">ژاڤرک</option><option value="en">English</option><option value="fa">فارسی</option></select>';
const fs=document.getElementById('fromSelect'),ts=document.getElementById('toSelect');fs.value='fa';ts.value='zv';fs.onchange=()=>setLanguages(fs.value,ts.value);ts.onchange=()=>setLanguages(fs.value,ts.value);
document.getElementById('input').addEventListener('input',update3);document.getElementById('translate').onclick=update3;document.getElementById('swap').onclick=()=>{const x=fs.value;fs.value=ts.value;ts.value=x;setLanguages(fs.value,ts.value)};document.getElementById('swap2').onclick=()=>{const x=fs.value;fs.value=ts.value;ts.value=x;setLanguages(fs.value,ts.value)};
document.querySelectorAll('.example-btn').forEach(b=>b.onclick=()=>{fs.value='fa';ts.value='zv';setLanguages('fa','zv');document.getElementById('input').value=b.dataset.fa;update3()});
renderMode();update3();
})();
